import './globals.css'
import { Inter } from 'next/font/google'
import ParticlesComponent from "../app/components/particles"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'iLunaweb',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <ParticlesComponent id="particles" /> 
      </body>
        
    </html>
  )
}
